### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by diiq** [22ndtech-admin/svelte-typescript-component#1]
Hey, @22ndtech-admin, thanks so much for putting this out here for people to see -- it solved my problems where no other template did.

Would you be willing to add an open-source license so I can crib from your `scripts/preprocess.js`? I don't want to steal your work, and I'm happy to reinvent the wheel if I need to, but if I *can* borrow, I will, and I imagine maybe some other people would, too.

Thanks!

**Comment by 22ndtech-admin** [comment]
Hey, @diiq thanks for giving me my very first issue... ever on any repo. It felt amazing when I saw it! I'm very glad that the work I did was able to help you. I've added a MIT LICENSE file.

Jeff
